image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - selenium  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - chmod +x ./gradlew
  - chmod +x ./artifacts/chromedriver
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-order.jar &

build_script:
  - ./gradlew test -Dselenide.headless=true --info  # запускаем тест, флаг --info позволяет выводить больше информации
